// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// NOTE:
// Lovable Cloud deployments may not expose Vite build-time env vars to the bundle.
// To avoid a production blank screen, we provide a hostname-based fallback for the
// public (anon) Supabase config. These values are public by design.
//
// IMPORTANT:
// We intentionally do NOT fallback on localhost to avoid accidentally pointing local
// dev environments at the production Supabase project.
const DEFAULT_PUBLIC_SUPABASE: { projectId: string; anonKey: string; url?: string } = {
  projectId: "sstxifqsickevprpuhap",
  anonKey:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdHhpZnFzaWNrZXZwcnB1aGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NzM3MDAsImV4cCI6MjA4NDE0OTcwMH0.yNYJflrpmmQatP6t0ClLIu2urvqpRfaMPDeC2FlOEZA",
};

const HOSTNAME_FALLBACKS: Record<
  string,
  { projectId: string; anonKey: string; url?: string }
> = {
  "videoremixpack.com": {
    ...DEFAULT_PUBLIC_SUPABASE,
  },
  "www.videoremixpack.com": {
    ...DEFAULT_PUBLIC_SUPABASE,
  },
};

function isLocalhostHostname(hostname: string): boolean {
  const lower = hostname.toLowerCase();
  return (
    lower === "localhost" ||
    lower === "127.0.0.1" ||
    lower === "0.0.0.0" ||
    lower === "[::1]" ||
    lower.endsWith(".localhost")
  );
}

function getFallbackForHostname(
  hostname: string | null | undefined
): { projectId: string; anonKey: string; url?: string } | undefined {
  if (!hostname) return undefined;

  const key = hostname.toLowerCase();
  const direct = HOSTNAME_FALLBACKS[key];
  if (direct) return direct;

  // NOTE:
  // Some hosting previews don't inject Vite build-time env vars into the bundle.
  // In that case, we fall back to the public (anon) Supabase config so the preview
  // can still load. We intentionally do NOT fallback on localhost to avoid
  // accidentally pointing local dev environments at the production Supabase project.
  if (!isLocalhostHostname(key)) return DEFAULT_PUBLIC_SUPABASE;

  return undefined;
}

function decodeJwtPayload(token: string): Record<string, unknown> | null {
  const parts = token.split('.');
  if (parts.length !== 3) return null;

  try {
    // JWT uses base64url encoding
    const base64 = parts[1].replace(/-/g, '+').replace(/_/g, '/');
    const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, '=');
    const json = atob(padded);
    const parsed = JSON.parse(json) as unknown;
    if (!parsed || typeof parsed !== 'object') return null;
    return parsed as Record<string, unknown>;
  } catch {
    return null;
  }
}

const env = import.meta.env;

const hostnameFallback =
  typeof window !== "undefined" ? getFallbackForHostname(window.location.hostname) : undefined;

export const supabaseAnonKey =
  env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  env.VITE_SUPABASE_ANON_KEY ||
  env.VITE_PUBLIC_SUPABASE_ANON_KEY ||
  env.VITE_PUBLIC_SUPABASE_KEY ||
  hostnameFallback?.anonKey;

const projectId =
  env.VITE_SUPABASE_PROJECT_ID ||
  env.VITE_PUBLIC_SUPABASE_PROJECT_ID ||
  hostnameFallback?.projectId;

const refFromKey = (() => {
  if (!supabaseAnonKey) return null;
  const payload = decodeJwtPayload(supabaseAnonKey);
  const ref = payload?.ref;
  return typeof ref === 'string' && ref.length > 0 ? ref : null;
})();

export const supabaseUrl =
  env.VITE_SUPABASE_URL ||
  env.VITE_PUBLIC_SUPABASE_URL ||
  hostnameFallback?.url ||
  (projectId ? `https://${projectId}.supabase.co` : undefined) ||
  (refFromKey ? `https://${refFromKey}.supabase.co` : undefined);

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Supabase configuration missing. Set VITE_SUPABASE_URL (or VITE_SUPABASE_PROJECT_ID) and VITE_SUPABASE_ANON_KEY.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
